# Generated by Django 5.0 on 2024-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_joblisting_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company',
            field=models.CharField(default='', max_length=255),
        ),
    ]
