# Generated by Django 5.0 on 2024-07-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_joblisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobcategory'),
        ),
    ]
